### ISSUE TITLE
[FE] 프로젝트 구조 변경 건

### ISSUE THREAD

**Issue by ppamppamman** [bibi6666667/airbnb#37]
- hooks 디렉토리 util 디렉토리 안쪽으로 넣읍시다.
![image](https://user-images.githubusercontent.com/13144573/120419100-bd1c6000-c39c-11eb-97da-de4e7cfa489f.png)

**Comment by 17-sss** [comment]
@ppamppamman  알겠소이다!

아까 의논했듯이 
현재 제 로컬에선 
기존 hooks 폴더는 제거했어요!

그리고 
모든 `useCalendar` `useCanvasSize` (실질적으론 Reducer 인 아이들)
모두 util의 reduce 폴더로 이동하고 이름 변경되었어요!
useCalendar는 calendar로, useCanvasSize는 canvasSize로!
